# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AppDeploymentProject' do
  pod 'TesseractOCRiOS', '4.0.0'
  use_frameworks!
  


  # Pods for AppDeploymentProject

  target 'AppDeploymentProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppDeploymentProjectUITests' do
    inherit! :search_paths
    # Pods for testing
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
    
  end

end
